# Generated by Django 4.1.2 on 2022-10-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haltestelle',
            name='hid',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
