# Generated by Django 4.1.2 on 2022-10-24 12:28

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_haltestelle_hid'),
    ]

    operations = [
    ]
