# Generated by Django 4.1.2 on 2022-10-24 13:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20221024_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haltestelle',
            name='location',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
